const state={days:30,category:'全部',query:'',match:'any',field:'all',offset:0,limit:30,openedAt:new Date(),refreshing:false,hunterAlert:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const colors={'出售':'#22d3c5','出售+求购':'#c39cf4','部分已出':'#8bcf9b','已出':'#65d68b','求购':'#f2bd63','待确认':'#566874'};
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n??0);
const money=n=>n==null?'—':'¥'+new Intl.NumberFormat('zh-CN',{maximumFractionDigits:0}).format(n);
const localTime=s=>{if(!s)return'—';const d=new Date(s);return d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})};
async function api(path,options){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||data.message||'请求失败');return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}

async function loadSummary(){const d=await api(`/api/summary?days=${state.days}`);$('#kpiPosts').textContent=fmt(d.kpis.posts);$('#kpiScanned').textContent=`累计扫描 ${fmt(d.scan.total_scanned)}`;$('#kpiSoldRate').textContent=d.kpis.sold_rate+'%';$('#kpiSold').textContent=fmt(d.kpis.sold);$('#kpiPrice').textContent=money(d.kpis.median_price);$('#kpiUsers').textContent=fmt(d.kpis.users);$('#kpiComments').textContent=fmt(d.kpis.comments);$('#coverageImages').textContent=fmt(d.kpis.images);$('#coverageLinks').textContent=fmt(d.kpis.xianyu_links);$('#latestTid').textContent=d.latest_tid||'—';$('#syncLastId').textContent=d.scan.last_recorded_id||'—';$('#syncNextId').textContent=d.scan.last_recorded_id?d.scan.last_recorded_id+1:'—';$('#avgPrice').textContent='均价 '+money(d.kpis.average_price);renderTrend(d.daily);renderDonut(d.categories,d.kpis.items);renderTerms(d.hot_terms);renderBars('#priceBands',d.price_bands);renderUsers(d.top_users)}
async function loadDaily(){const d=await api(`/api/daily?limit=${Math.min(state.days,365)}`);$('#dailyRows').innerHTML=d.items.length?d.items.map(dailyRow).join(''):'<div class="daily-empty">采集到帖子后将自动生成每日盘数据</div>'}
function dailyRow(x){const change=x.post_change_pct==null?'—':`${x.post_change_pct>0?'+':''}${x.post_change_pct}%`;const cls=x.post_change_pct>0?'up':x.post_change_pct<0?'down':'';return `<div class="daily-row"><span class="daily-day"><strong>${esc(x.day)}</strong><small>${x.first_tid}—${x.last_tid}</small></span><span class="daily-number">${fmt(x.posts)}</span><span class="daily-categories">${x.selling} / ${x.sold} / ${x.wanted}</span><span>${x.sold_rate}%</span><span class="daily-number">${money(x.median_price)}</span><span>${fmt(x.active_users)}</span><span>${x.comments} / ${x.xianyu_links}</span><span class="daily-change ${cls}">${change}</span></div>`}
function renderTrend(rows){const canvas=$('#trendChart'),empty=$('#trendEmpty');const has=rows.some(r=>r['出售']+r['已出']+r['求购']>0);canvas.style.display=has?'block':'none';empty.style.display=has?'none':'grid';if(!has)return;const ratio=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,w,h);const pad={l:36,r:10,t:12,b:28},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;const max=Math.max(1,...rows.flatMap(r=>[r['出售'],r['已出'],r['求购']]));c.strokeStyle='#1e2a32';c.lineWidth=1;c.fillStyle='#71838e';c.font='11px Segoe UI';for(let i=0;i<=4;i++){const y=pad.t+ch*i/4;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(Math.round(max*(1-i/4)),3,y+3)}const keys=['出售','已出','求购'];keys.forEach(key=>{c.strokeStyle=colors[key];c.lineWidth=2;c.beginPath();rows.forEach((r,i)=>{const x=pad.l+(rows.length===1?cw/2:cw*i/(rows.length-1)),y=pad.t+ch-(r[key]/max)*ch;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()});const step=Math.max(1,Math.ceil(rows.length/6));c.fillStyle='#71838e';rows.forEach((r,i)=>{if(i%step===0||i===rows.length-1)c.fillText(r.date.slice(5),pad.l+cw*i/Math.max(1,rows.length-1)-14,h-6)})}
function renderDonut(items,total){$('#donutTotal').textContent=fmt(total);let cursor=0,segments=[];items.forEach(x=>{const start=total?cursor/total*100:0;cursor+=x.value;const end=total?cursor/total*100:0;segments.push(`${colors[x.name]} ${start}% ${end}%`)});$('#categoryDonut').style.background=total?`conic-gradient(${segments.join(',')})`:'#1c2830';$('#categoryLegend').innerHTML=items.map(x=>`<div><i style="background:${colors[x.name]}"></i><span>${x.name}</span><strong>${fmt(x.value)}</strong></div>`).join('')}
function renderTerms(items){const max=Math.max(1,...items.map(x=>x.value));$('#hotTerms').innerHTML=items.length?items.map((x,i)=>`<span class="term ${i<5?'hot':''}" style="font-size:${9+Math.round(x.value/max*4)}px">${esc(x.name)} · ${x.value}</span>`).join(''):'<span class="term">等待数据</span>'}
function renderBars(selector,items){const max=Math.max(1,...items.map(x=>x.value));$(selector).innerHTML=items.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar-track"><div class="bar-fill" style="width:${x.value/max*100}%"></div></div><strong>${x.value}</strong></div>`).join('')}
function renderUsers(items){const max=Math.max(1,...items.map(x=>x.value));$('#topUsers').innerHTML=items.length?items.map((x,i)=>`<div class="rank-row"><span>${String(i+1).padStart(2,'0')}</span><span class="name">${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.value/max*100}%"></div></div><strong>${x.value}</strong></div>`).join(''):'<span class="term">等待数据</span>'}

async function loadPosts(reset=true){if(reset){state.offset=0;$('#postList').innerHTML=''}const q=new URLSearchParams({limit:state.limit,offset:state.offset,category:state.category,q:state.query,match:state.match,field:state.field});const d=await api('/api/posts?'+q);$('#postCount').textContent=fmt(d.total)+' 条';const html=d.items.map(postRow).join('');$('#postList').insertAdjacentHTML('beforeend',html);state.offset+=d.items.length;$('#loadMore').style.display=state.offset<d.total?'block':'none';$$('.post-row').forEach(row=>row.onclick=e=>showPost(row.dataset.tid,Boolean(e.target.closest('.quick-locate'))))}
function postRow(p){const d=new Date(p.created_at),isNew=d>=state.openedAt;const statusClass=p.category==='出售'?'selling':p.category==='求购'?'wanted':p.category==='部分已出'?'partial':p.category==='出售+求购'?'mixed':'';const prices=p.prices?.length?p.prices.slice(0,2).map(x=>'¥'+x).join(' / '):'—';const locate=state.query?'<button class="quick-locate" type="button">快速定位</button>':'';const details=p.item_details||[],sale=details.filter(x=>x.status==='出售'||x.status==='已出'),wanted=details.filter(x=>x.status==='求购');const mixed=sale.length&&wanted.length?`<small class="item-summary selling-line"><b>出售</b>${sale.map(x=>esc(x.name)+(x.status==='已出'?'（已出）':'')).join('、')}</small><small class="item-summary wanted-line"><b>求购</b>${wanted.map(x=>esc(x.name)).join('、')}</small>`:'';const excluded=p.search_excluded?`<small class="excluded-note">排除：${esc((p.search_excluded_terms||[]).join('、'))}仅出现在否定语境</small>`:'';return `<div class="post-row ${p.search_excluded?'excluded-result':''}" data-tid="${p.tid}"><div class="post-title"><div class="post-title-copy"><strong>${esc(p.title)}${isNew?'<span class="new-tag">NEW</span>':''}</strong>${mixed}${excluded}<small class="post-meta">${esc(p.username||'未知')} · TID ${p.tid}${locate}</small></div></div><span class="status-tag ${statusClass}">${p.search_excluded?'排除':esc(p.category)}</span><span class="price-cell">${prices}</span><span class="time-cell">${localTime(p.created_at)}</span></div>`}
async function showPost(tid,locate=false,query=state.query){const p=await api('/api/posts/'+tid),paint=v=>locate?highlightText(v,query):esc(v);if(locate)$('#detailTitle').innerHTML=paint(p.title);else $('#detailTitle').textContent=p.title;const links=[...(p.xianyu_links||[]),...(p.links||[]).filter(x=>!(p.xianyu_links||[]).includes(x))];const items=(p.item_details?.length?p.item_details:(p.items||[]).map((name,i)=>({index:i+1,name,status:p.category,prices:[]})));$('#detailBody').innerHTML=`<div class="detail-meta"><span class="status-tag">${esc(p.category)}</span><span class="count-pill">${paint(p.username)}</span><span class="count-pill">${localTime(p.created_at)}</span><a class="count-pill" href="${attr(p.url)}" target="_blank">原帖 ↗</a></div><div class="detail-content">${paint(p.content||'无正文')}</div>${section(`物品明细 ${items.length}`,items.map(item=>`<div class="item-card"><span class="item-index">${item.index}</span><div><strong>${paint(item.name)}</strong>${item.prices?.length?`<small>${item.prices.map(x=>'¥'+esc(x)).join(' / ')}</small>`:''}</div><span class="item-status ${item.status==='已出'?'sold':item.status==='求购'?'wanted':'selling'}">${esc(item.status)}</span></div>`).join(''))}${section('帖子图片',p.images?.length?`<div class="image-grid">${p.images.map((x,i)=>{const proxy=imageUrl(x);return `<button class="image-button" type="button" data-src="${attr(proxy)}" data-alt="帖子图片 ${i+1}"><img src="${attr(proxy)}" alt="帖子图片 ${i+1}" loading="lazy" decoding="async"><span>点击放大</span></button>`}).join('')}</div>`:'')}${section('链接',links.length?`<div class="detail-links">${links.map(x=>`<a href="${attr(x)}" target="_blank">${esc(x)}</a>`).join('')}</div>`:'')}${section(`评论 ${p.comments?.length||0}`,p.comments?.map(c=>`<div class="comment"><strong>${paint(c.username||'未知')}</strong><p>${paint(c.content)}</p></div>`).join(''))}`;openDrawer();if(locate)requestAnimationFrame(()=>{const hit=$('#detailDrawer .keyword-hit');if(hit)hit.scrollIntoView({behavior:'smooth',block:'center'})})}
function section(title,body){return body?`<div class="detail-section"><h3>${title}</h3>${body}</div>`:''}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(v=''){return esc(v)}function queryTerms(v=''){return [...new Set(String(v).split(/[\s,，、;；]+/).map(x=>x.trim()).filter(Boolean))].sort((a,b)=>b.length-a.length)}function highlightText(v,q){const words=queryTerms(q);if(!words.length)return esc(v);const source=words.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),re=new RegExp(`(${source})`,'gi');return String(v??'').split(re).map((part,i)=>i%2?`<mark class="keyword-hit">${esc(part)}</mark>`:esc(part)).join('')}function imageUrl(v=''){return '/api/image?url='+encodeURIComponent(v)}
function openDrawer(){$('#detailDrawer').classList.add('open');$('#backdrop').classList.add('open');$('#detailDrawer').setAttribute('aria-hidden','false')}function closeDrawer(){closeLightbox();$('#detailDrawer').classList.remove('open');$('#backdrop').classList.remove('open');$('#detailDrawer').setAttribute('aria-hidden','true')}function openLightbox(src,alt){$('#lightboxImage').src=src;$('#lightboxImage').alt=alt;$('#imageLightbox').classList.add('open');$('#imageLightbox').setAttribute('aria-hidden','false')}function closeLightbox(){$('#imageLightbox').classList.remove('open');$('#imageLightbox').setAttribute('aria-hidden','true');$('#lightboxImage').removeAttribute('src')}

async function refreshLatest(manual=false){if(state.refreshing)return;state.refreshing=true;$('#refreshBtn').disabled=true;$('#refreshBtn').innerHTML='<span>↻</span> 追赶中';try{const result=await api('/api/tasks/refresh',{method:'POST',body:JSON.stringify({batch:64,max_catchup:10000,refresh_recent:10,workers:8,comments:true,max_comment_pages:5})});if(manual)toast(result.message);await waitTask();await Promise.all([loadSummary(),loadDaily(),loadPosts(true)])}catch(e){if(manual)toast(e.message);else await Promise.all([loadSummary(),loadDaily(),loadPosts(true)])}finally{state.refreshing=false;$('#refreshBtn').disabled=false;$('#refreshBtn').innerHTML='<span>↻</span> 刷新最新'}}
async function waitTask(){for(let i=0;i<90;i++){const t=await loadTask();if(!t.running)return t;await new Promise(r=>setTimeout(r,1000))}}
async function loadTask(){const t=await api('/api/task');$('#sideStatus').textContent=t.message;$('#statusDot').classList.toggle('running',t.running);$('#taskPulse').classList.toggle('running',t.running);$('#taskMode').textContent=(t.mode||'IDLE').toUpperCase();$('#taskMessage').textContent=t.message;$('#taskProcessed').textContent=fmt(t.processed);$('#taskMatched').textContent=fmt(t.matched);$('#taskLastTid').textContent=t.last_tid||'—';$('#taskElapsed').textContent=(t.elapsed_seconds||0)+'s';$('#taskError').textContent=t.error||'';$('#taskProgress').classList.toggle('indeterminate',t.running);if(t.last_recorded_id){$('#syncLastId').textContent=t.last_recorded_id;$('#syncNextId').textContent=t.last_recorded_id+1}return t}
async function loadHunter(){const h=await api('/api/hunter');$('#hunterBadge').textContent=h.active?'ACTIVE':'IDLE';$('#hunterBadge').classList.toggle('live',h.active);$('#hunterPulse').classList.toggle('running',h.active);$('#hunterMessage').textContent=h.message;$('#hunterChecks').textContent=fmt(h.checks);$('#hunterMatches').textContent=fmt(h.total_matches);$('#hunterNewHits').textContent=fmt(h.new_hits);$('#hunterNext').textContent=h.next_check_at?new Date(h.next_check_at).toLocaleTimeString('zh-CN',{hour12:false}):'—';$('#hunterError').textContent=h.error||'';$('#hunterStart').disabled=h.active;$('#hunterStop').disabled=!h.active;const results=h.results||[];$('#hunterResultCount').textContent=fmt(results.length)+' 条';$('#hunterResults').innerHTML=results.length?results.map(p=>`<div class="hunter-result ${p.search_excluded?'excluded-result':''}" data-tid="${p.tid}"><div><strong>${esc(p.title)}</strong><small>${esc(p.username||'未知')} · TID ${p.tid}${p.search_excluded?' · 否定语境排除':''}</small></div><span class="status-tag">${p.search_excluded?'排除':esc(p.category)}</span><span class="time-cell">${localTime(p.created_at)}</span></div>`).join(''):'<div class="daily-empty">尚未命中结果</div>';$$('.hunter-result').forEach(row=>row.onclick=()=>showPost(row.dataset.tid,true,h.config?.q||''));if(h.alert_id>state.hunterAlert){state.hunterAlert=h.alert_id;const hits=h.latest_hits||[];const message=hits.length?`发现 ${hits.length} 条符合条件的帖子`:'市场猎手发现新结果';toast(message);if('Notification'in window&&Notification.permission==='granted')new Notification('SDGun 市场猎手',{body:hits[0]?.title||message,tag:'sdgun-hunter-'+h.alert_id})}return h}
async function startHunter(){const q=$('#hunterQuery').value.trim();if(!q)return toast('请先输入猎手关键词');if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();const payload={q,match:$('#hunterMatch').value,field:$('#hunterField').value,category:$('#hunterCategory').value,interval:Number($('#hunterInterval').value||30)};try{const r=await api('/api/hunter/start',{method:'POST',body:JSON.stringify(payload)});toast(r.message);await loadHunter()}catch(e){toast(e.message)}}
async function stopHunter(){const r=await api('/api/hunter/stop',{method:'POST',body:'{}'});toast(r.message);await loadHunter()}
function navigate(id){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.target===id));$$('.section').forEach(x=>x.classList.toggle('active-section',x.id===id));if(id==='posts')loadPosts(true);if(id==='hunter')loadHunter();window.scrollTo({top:0})}
function updateSearchHint(){const mode=state.match==='all'?'每个关键词都必须':'任意关键词可以';const field={all:'出现在标题、作者、正文或物品明细中',title:'出现在帖子标题中',author:'出现在作者名称中'}[state.field];$('#searchHint').textContent=mode+field;$('#searchInput').placeholder=state.field==='title'?'输入一个或多个标题关键词':state.field==='author'?'输入一个或多个作者关键词':'多关键词：用空格、逗号或顿号分隔'}

function bind(){$$('.nav-item').forEach(x=>x.onclick=()=>navigate(x.dataset.target));$('#controlBtn').onclick=()=>navigate('control');$('#refreshBtn').onclick=()=>refreshLatest(true);$('#syncNow').onclick=()=>refreshLatest(true);$('#hunterStart').onclick=startHunter;$('#hunterStop').onclick=stopHunter;$('#closeDrawer').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#lightboxClose').onclick=closeLightbox;$('#imageLightbox').onclick=e=>{if(e.target.id==='imageLightbox')closeLightbox()};$('#detailBody').onclick=e=>{const b=e.target.closest('.image-button');if(b)openLightbox(b.dataset.src,b.dataset.alt)};document.onkeydown=e=>{if(e.key==='Escape'){$('#imageLightbox').classList.contains('open')?closeLightbox():closeDrawer()}};$('#periodPicker').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#periodPicker button').forEach(x=>x.classList.toggle('active',x===b));state.days=Number(b.dataset.days);Promise.all([loadSummary(),loadDaily()])};$('#categoryFilter').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#categoryFilter button').forEach(x=>x.classList.toggle('active',x===b));state.category=b.dataset.category;loadPosts(true)};$('#matchMode').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#matchMode button').forEach(x=>x.classList.toggle('active',x===b));state.match=b.dataset.match;updateSearchHint();loadPosts(true)};$('#searchField').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#searchField button').forEach(x=>x.classList.toggle('active',x===b));state.field=b.dataset.field;updateSearchHint();loadPosts(true)};let searchTimer;$('#searchInput').oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=e.target.value.trim();loadPosts(true)},280)};$('#loadMore').onclick=()=>loadPosts(false);$('#stopTask').onclick=async()=>{const r=await api('/api/tasks/stop',{method:'POST',body:'{}'});toast(r.message);loadTask()};window.addEventListener('resize',()=>loadSummary());updateSearchHint()}
async function init(){state.openedAt=new Date();$('#openedAt').textContent=state.openedAt.toLocaleString('zh-CN',{hour12:false});bind();await Promise.all([loadSummary(),loadDaily(),loadPosts(true),loadTask(),loadHunter()]);setInterval(loadTask,2000);setInterval(loadHunter,5000);refreshLatest(false)}
init().catch(e=>toast(e.message));
