const savedWorkers=Number(localStorage.getItem('sdgun-sync-workers'));
const savedSyncPostType=localStorage.getItem('sdgun-sync-post-type')||'二手出售';
const state={days:30,postType:'二手出售',syncPostType:['二手出售','求购','召集团购','商家广告','全部'].includes(savedSyncPostType)?savedSyncPostType:'二手出售',category:'全部',query:'',match:'any',field:'all',offset:0,limit:30,openedAt:new Date(),refreshing:false,hunterAlerts:{},hunterEditing:null,detailTid:null,workers:[4,8,16,24,32].includes(savedWorkers)?savedWorkers:16};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const colors={'出售':'#22d3c5','出售+求购':'#c39cf4','部分已出':'#8bcf9b','已出':'#65d68b','求购':'#f2bd63','待确认':'#566874'};
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n??0);
const money=n=>n==null?'—':'¥'+new Intl.NumberFormat('zh-CN',{maximumFractionDigits:0}).format(n);
const localTime=s=>{if(!s)return'—';const d=new Date(s);return d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})};
async function api(path,options){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||data.message||'请求失败');return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}

async function loadSummary(){const d=await api(`/api/summary?days=${state.days}`);$('#kpiPosts').textContent=fmt(d.kpis.posts);$('#kpiScanned').textContent=`累计扫描 ${fmt(d.scan.total_scanned)}`;$('#kpiSoldRate').textContent=d.kpis.sold_rate+'%';$('#kpiSold').textContent=fmt(d.kpis.sold);$('#kpiPrice').textContent=money(d.kpis.median_price);$('#kpiUsers').textContent=fmt(d.kpis.users);$('#kpiComments').textContent=fmt(d.kpis.comments);$('#coverageImages').textContent=fmt(d.kpis.images);$('#coverageLinks').textContent=fmt(d.kpis.xianyu_links);$('#latestTid').textContent=d.latest_tid||'—';$('#syncLastId').textContent=d.scan.last_recorded_id||'—';$('#syncNextId').textContent=d.scan.last_recorded_id?d.scan.last_recorded_id+1:'—';$('#avgPrice').textContent='均价 '+money(d.kpis.average_price);renderTrend(d.daily);renderDonut(d.categories,d.kpis.items);renderTerms(d.hot_terms);renderBars('#priceBands',d.price_bands);renderUsers(d.top_users)}
async function loadDaily(){const d=await api(`/api/daily?limit=${Math.min(state.days,365)}`);$('#dailyRows').innerHTML=d.items.length?d.items.map(dailyRow).join(''):'<div class="daily-empty">采集到帖子后将自动生成每日盘数据</div>'}
function dailyRow(x){const change=x.post_change_pct==null?'—':`${x.post_change_pct>0?'+':''}${x.post_change_pct}%`;const cls=x.post_change_pct>0?'up':x.post_change_pct<0?'down':'';return `<div class="daily-row"><span class="daily-day"><strong>${esc(x.day)}</strong><small>${x.first_tid}—${x.last_tid}</small></span><span class="daily-number">${fmt(x.posts)}</span><span class="daily-categories">${x.selling} / ${x.sold} / ${x.wanted}</span><span>${x.sold_rate}%</span><span class="daily-number">${money(x.median_price)}</span><span>${fmt(x.active_users)}</span><span>${x.comments} / ${x.xianyu_links}</span><span class="daily-change ${cls}">${change}</span></div>`}
function renderTrend(rows){const canvas=$('#trendChart'),empty=$('#trendEmpty');const has=rows.some(r=>r['出售']+r['已出']+r['求购']>0);canvas.style.display=has?'block':'none';empty.style.display=has?'none':'grid';if(!has)return;const ratio=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,w,h);const pad={l:36,r:10,t:12,b:28},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;const max=Math.max(1,...rows.flatMap(r=>[r['出售'],r['已出'],r['求购']]));c.strokeStyle='#1e2a32';c.lineWidth=1;c.fillStyle='#71838e';c.font='11px Segoe UI';for(let i=0;i<=4;i++){const y=pad.t+ch*i/4;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(Math.round(max*(1-i/4)),3,y+3)}const keys=['出售','已出','求购'];keys.forEach(key=>{c.strokeStyle=colors[key];c.lineWidth=2;c.beginPath();rows.forEach((r,i)=>{const x=pad.l+(rows.length===1?cw/2:cw*i/(rows.length-1)),y=pad.t+ch-(r[key]/max)*ch;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()});const step=Math.max(1,Math.ceil(rows.length/6));c.fillStyle='#71838e';rows.forEach((r,i)=>{if(i%step===0||i===rows.length-1)c.fillText(r.date.slice(5),pad.l+cw*i/Math.max(1,rows.length-1)-14,h-6)})}
function renderDonut(items,total){$('#donutTotal').textContent=fmt(total);let cursor=0,segments=[];items.forEach(x=>{const start=total?cursor/total*100:0;cursor+=x.value;const end=total?cursor/total*100:0;segments.push(`${colors[x.name]} ${start}% ${end}%`)});$('#categoryDonut').style.background=total?`conic-gradient(${segments.join(',')})`:'#1c2830';$('#categoryLegend').innerHTML=items.map(x=>`<div><i style="background:${colors[x.name]}"></i><span>${x.name}</span><strong>${fmt(x.value)}</strong></div>`).join('')}
function renderTerms(items){const max=Math.max(1,...items.map(x=>x.value));$('#hotTerms').innerHTML=items.length?items.map((x,i)=>`<span class="term ${i<5?'hot':''}" style="font-size:${9+Math.round(x.value/max*4)}px">${esc(x.name)} · ${x.value}</span>`).join(''):'<span class="term">等待数据</span>'}
function renderBars(selector,items){const max=Math.max(1,...items.map(x=>x.value));$(selector).innerHTML=items.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar-track"><div class="bar-fill" style="width:${x.value/max*100}%"></div></div><strong>${x.value}</strong></div>`).join('')}
function renderUsers(items){const max=Math.max(1,...items.map(x=>x.value));$('#topUsers').innerHTML=items.length?items.map((x,i)=>`<div class="rank-row"><span>${String(i+1).padStart(2,'0')}</span><span class="name">${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.value/max*100}%"></div></div><strong>${x.value}</strong></div>`).join(''):'<span class="term">等待数据</span>'}

async function loadPosts(reset=true){if(reset){state.offset=0;$('#postList').innerHTML=''}const q=new URLSearchParams({limit:state.limit,offset:state.offset,post_type:state.postType,category:state.category,q:state.query,match:state.match,field:state.field});const d=await api('/api/posts?'+q);$('#postCount').textContent=fmt(d.total)+' 条';const html=d.items.map(postRow).join('');$('#postList').insertAdjacentHTML('beforeend',html);state.offset+=d.items.length;$('#loadMore').style.display=state.offset<d.total?'block':'none';$$('.post-row').forEach(row=>row.onclick=e=>{const favorite=e.target.closest('.favorite-button');if(favorite){e.stopPropagation();return toggleFavorite(row.dataset.tid,favorite)}showPost(row.dataset.tid,Boolean(e.target.closest('.quick-locate')))})}
function postRow(p){const d=new Date(p.created_at),isNew=d>=state.openedAt;const statusClass=p.category==='出售'?'selling':p.category==='求购'?'wanted':p.category==='部分已出'?'partial':p.category==='出售+求购'?'mixed':'';const prices=p.prices?.length?p.prices.slice(0,2).map(x=>'¥'+x).join(' / '):'—';const locate=state.query?'<button class="quick-locate" type="button">快速定位</button>':'';const details=p.item_details||[],sale=details.filter(x=>x.status==='出售'||x.status==='已出'),wanted=details.filter(x=>x.status==='求购');const mixed=sale.length&&wanted.length?`<small class="item-summary selling-line"><b>出售</b>${sale.map(x=>esc(x.name)+(x.status==='已出'?'（已出）':'')).join('、')}</small><small class="item-summary wanted-line"><b>求购</b>${wanted.map(x=>esc(x.name)).join('、')}</small>`:'';const excluded=p.search_excluded?`<small class="excluded-note">排除：${esc((p.search_excluded_terms||[]).join('、'))}仅出现在否定语境</small>`:'';return `<div class="post-row ${p.search_excluded?'excluded-result':''}" data-tid="${p.tid}"><div class="post-title"><div class="post-title-copy"><strong>${esc(p.title)}${isNew?'<span class="new-tag">NEW</span>':''}</strong>${mixed}${excluded}<small class="post-meta">${esc(p.post_type||'二手出售')} · ${esc(p.username||'未知')} · TID ${p.tid}${locate}</small></div></div><span class="status-tag ${statusClass}">${p.search_excluded?'排除':esc(p.category)}</span><span class="price-cell">${prices}</span><span class="time-cell">${localTime(p.created_at)}</span><button class="favorite-button ${p.is_favorite?'active':''}" type="button" aria-label="${p.is_favorite?'取消收藏':'收藏帖子'}" aria-pressed="${Boolean(p.is_favorite)}">★</button></div>`}
function sdgunThreadLink(value){try{const url=new URL(value);if(url.hostname.toLowerCase()!=='app.sdgun.com.cn'||url.pathname.toLowerCase()!=='/mag/circle/v1/forum/threadwappage')return null;const tid=url.searchParams.get('tid');return /^\d+$/.test(tid||'')?{tid,url:value}:null}catch{return null}}
async function showPost(tid,locate=false,query=state.query){const p=await api('/api/posts/'+tid),paint=v=>locate?highlightText(v,query):esc(v);if(locate)$('#detailTitle').innerHTML=paint(p.title);else $('#detailTitle').textContent=p.title;const videos=p.videos||[],posters=new Set(p.video_posters||[]),images=(p.images||[]).filter(x=>!posters.has(x)),links=[...(p.xianyu_links||[]),...(p.links||[]).filter(x=>!(p.xianyu_links||[]).includes(x)&&!videos.includes(x))],jumpLinks=links.map(sdgunThreadLink).filter(Boolean),regularLinks=links.filter(x=>!sdgunThreadLink(x));const items=(p.item_details?.length?p.item_details:(p.items||[]).map((name,i)=>({index:i+1,name,status:p.category,prices:[]})));$('#detailBody').innerHTML=`<div class="detail-meta"><span class="status-tag">${esc(p.category)}</span><span class="count-pill">${paint(p.username)}</span><span class="count-pill">${localTime(p.created_at)}</span><a class="count-pill" href="${attr(p.url)}" target="_blank">原帖 ↗</a><button class="count-pill detail-refresh" type="button" data-refresh-tid="${p.tid}">↻ 更新状态</button></div><div class="detail-content">${paint(p.content||'无正文')}</div>${section(`物品明细 ${items.length}`,items.map(item=>`<div class="item-card"><span class="item-index">${item.index}</span><div><strong>${paint(item.name)}</strong>${item.prices?.length?`<small>${item.prices.map(x=>'¥'+esc(x)).join(' / ')}</small>`:''}</div><span class="item-status ${item.status==='已出'?'sold':item.status==='求购'?'wanted':'selling'}">${esc(item.status)}</span></div>`).join(''))}${section('帖子视频',videos.length?`<div class="video-grid">${videos.map((x,i)=>`<video controls preload="metadata" playsinline src="${attr(videoUrl(x))}" aria-label="帖子视频 ${i+1}"></video>`).join('')}</div>`:'')}${section('帖子图片',images.length?`<div class="image-grid">${images.map((x,i)=>{const proxy=imageUrl(x);return `<button class="image-button" type="button" data-src="${attr(proxy)}" data-alt="帖子图片 ${i+1}"><img src="${attr(proxy)}" alt="帖子图片 ${i+1}" loading="lazy" decoding="async"><span>点击放大</span></button>`}).join('')}</div>`:'')}${section('跳转帖',jumpLinks.length?`<div class="detail-links">${jumpLinks.map(x=>`<button class="count-pill thread-jump" type="button" data-thread-tid="${x.tid}" data-thread-url="${attr(x.url)}">查看跳转帖 · TID ${x.tid} →</button>`).join('')}</div>`:'')}${section('其他链接',regularLinks.length?`<div class="detail-links">${regularLinks.map(x=>`<a href="${attr(x)}" target="_blank" rel="noopener">${esc(x)}</a>`).join('')}</div>`:'')}${section(`评论 ${p.comments?.length||0}`,p.comments?.map(c=>`<div class="comment"><strong>${paint(c.username||'未知')}</strong><p>${paint(c.content)}</p></div>`).join(''))}`;openDrawer();if(locate)requestAnimationFrame(()=>{const hit=$('#detailDrawer .keyword-hit');if(hit)hit.scrollIntoView({behavior:'smooth',block:'center'})})}
async function refreshPost(tid,button){button.disabled=true;button.textContent='↻ 更新中…';try{const result=await api('/api/posts/'+tid+'/refresh',{method:'POST',body:'{}'});toast(result.message);await Promise.all([showPost(tid),loadPosts(true),loadSummary(),loadDaily()])}catch(e){toast(e.message);button.disabled=false;button.textContent='↻ 更新状态'}}
document.addEventListener('click',async e=>{const refresh=e.target.closest('.detail-refresh');if(refresh)return refreshPost(refresh.dataset.refreshTid,refresh);const jump=e.target.closest('.thread-jump');if(jump){try{await showPost(jump.dataset.threadTid)}catch{window.open(jump.dataset.threadUrl,'_blank','noopener')}}})
async function toggleFavorite(tid,button){const favorite=!button.classList.contains('active');try{await api('/api/favorites/'+tid,{method:'POST',body:JSON.stringify({favorite})});button.classList.toggle('active',favorite);button.setAttribute('aria-pressed',String(favorite));button.setAttribute('aria-label',favorite?'取消收藏':'收藏帖子');toast(favorite?'已收藏帖子':'已取消收藏');if($('#favorites').classList.contains('active-section'))await loadFavorites()}catch(e){toast(e.message)}}
async function loadFavorites(){const d=await api('/api/favorites');$('#favoriteCount').textContent=fmt(d.total)+' 条';$('#favoriteList').innerHTML=d.items.length?d.items.map(favoriteCard).join(''):'<div class="daily-empty">暂无收藏帖子</div>';$$('.favorite-card').forEach(card=>{card.querySelector('.favorite-open').onclick=()=>showPost(card.dataset.tid);card.querySelector('.favorite-remove').onclick=()=>toggleFavorite(card.dataset.tid,card.querySelector('.favorite-remove'));card.querySelector('.favorite-note-save').onclick=()=>saveFavoriteNote(card)})}
function favoriteCard(p){const prices=p.prices?.length?p.prices.slice(0,2).map(x=>'¥'+esc(x)).join(' / '):'—';return `<article class="panel favorite-card" data-tid="${p.tid}"><div class="favorite-card-head"><button class="favorite-open" type="button"><strong>${esc(p.title)}</strong><small>${esc(p.username||'未知')} · TID ${p.tid} · ${localTime(p.created_at)}</small></button><div><span class="status-tag">${esc(p.category)}</span><span class="favorite-price">${prices}</span><button class="favorite-button favorite-remove active" type="button" aria-label="取消收藏" aria-pressed="true">★</button></div></div><label class="favorite-note"><span>备注</span><textarea maxlength="1000" placeholder="记录价格、成色、联系情况等">${esc(p.note||'')}</textarea></label><div class="favorite-note-actions"><small>收藏于 ${localTime(p.favorited_at)}</small><button class="button favorite-note-save" type="button">保存备注</button></div></article>`}
async function saveFavoriteNote(card){const note=card.querySelector('textarea').value;try{await api('/api/favorites/'+card.dataset.tid,{method:'POST',body:JSON.stringify({note})});toast('备注已保存')}catch(e){toast(e.message)}}
function section(title,body){return body?`<div class="detail-section"><h3>${title}</h3>${body}</div>`:''}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(v=''){return esc(v)}function queryTerms(v=''){return [...new Set(String(v).split(/[\s,，、;；]+/).map(x=>x.trim()).filter(Boolean))].sort((a,b)=>b.length-a.length)}function highlightText(v,q){const words=queryTerms(q);if(!words.length)return esc(v);const source=words.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),re=new RegExp(`(${source})`,'gi');return String(v??'').split(re).map((part,i)=>i%2?`<mark class="keyword-hit">${esc(part)}</mark>`:esc(part)).join('')}function imageUrl(v=''){return '/api/image?url='+encodeURIComponent(v)}function videoUrl(v=''){return '/api/video?url='+encodeURIComponent(v)}
function openDrawer(){const drawer=$('#detailDrawer');if(!drawer.classList.contains('open')){document.body.style.overflow='hidden';$('#detailBody').style.overscrollBehavior='contain'}drawer.classList.add('open');$('#backdrop').classList.add('open');drawer.setAttribute('aria-hidden','false')}function closeDrawer(){closeLightbox();const drawer=$('#detailDrawer');if(!drawer.classList.contains('open'))return;drawer.classList.remove('open');$('#backdrop').classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}function openLightbox(src,alt){$('#lightboxImage').src=src;$('#lightboxImage').alt=alt;$('#imageLightbox').classList.add('open');$('#imageLightbox').setAttribute('aria-hidden','false')}function closeLightbox(){$('#imageLightbox').classList.remove('open');$('#imageLightbox').setAttribute('aria-hidden','true');$('#lightboxImage').removeAttribute('src')}

async function refreshLatest(manual=false){if(state.refreshing)return;state.refreshing=true;$('#refreshBtn').disabled=true;$('#refreshBtn').innerHTML='<span>↻</span> 追赶中';const postTypes=state.syncPostType==='全部'?['二手出售','求购','召集团购','商家广告']:[state.syncPostType];try{const result=await api('/api/tasks/refresh',{method:'POST',body:JSON.stringify({batch:Math.max(64,state.workers*4),forum_step:500,refresh_recent:0,workers:state.workers,post_types:postTypes,comments:false,media:false})});if(manual)toast(`${result.message}（${state.syncPostType} · ${state.workers} 线程）`);await waitTask();await Promise.all([loadSummary(),loadDaily(),loadPosts(true)])}catch(e){if(manual)toast(e.message);else await Promise.all([loadSummary(),loadDaily(),loadPosts(true)])}finally{state.refreshing=false;$('#refreshBtn').disabled=false;$('#refreshBtn').innerHTML='<span>↻</span> 刷新最新'}}
const renderPostBase=showPost;
const closeDrawerBase=closeDrawer;
const prefetchPromises=new Map();
const prefetchQueue=[];
const warmingImages=new Set();
let prefetchActive=0;
function runPrefetchQueue(){
  while(prefetchActive<2&&prefetchQueue.length){
    const job=prefetchQueue.shift();
    prefetchActive++;
    api(`/api/posts/${job.tid}/hydrate`,{method:'POST',body:'{}'})
      .then(p=>{
        (p.images||[]).slice(0,3).forEach(src=>{
          const image=new Image();
          warmingImages.add(image);
          image.onload=image.onerror=()=>warmingImages.delete(image);
          image.src=imageUrl(src);
        });
        job.resolve(p);
      },job.reject)
      .finally(()=>{prefetchActive--;runPrefetchQueue()});
  }
}
function prefetchPost(tid){
  tid=String(tid);
  if(prefetchPromises.has(tid))return prefetchPromises.get(tid);
  const promise=new Promise((resolve,reject)=>prefetchQueue.push({tid,resolve,reject}));
  prefetchPromises.set(tid,promise);
  promise.catch(()=>prefetchPromises.delete(tid));
  runPrefetchQueue();
  return promise;
}
const visiblePostObserver=new IntersectionObserver(entries=>{
  entries.forEach(entry=>{
    if(!entry.isIntersecting)return;
    visiblePostObserver.unobserve(entry.target);
    prefetchPost(entry.target.dataset.tid).catch(()=>{});
  });
},{root:null,rootMargin:'120px 0px',threshold:.01});
const postListMutationObserver=new MutationObserver(()=>{
  $$('#postList .post-row:not([data-prefetch-watched])').forEach(row=>{
    row.dataset.prefetchWatched='1';
    visiblePostObserver.observe(row);
  });
});
postListMutationObserver.observe($('#postList'),{childList:true});
showPost=async function(tid,locate=false,query=state.query){
  state.detailTid=String(tid);
  await renderPostBase(tid,locate,query);
  prefetchPost(tid).then(()=>{
    if(state.detailTid===String(tid)&&$('#detailDrawer').classList.contains('open')){
      renderPostBase(tid,locate,query);
    }
  }).catch(()=>{});
};
closeDrawer=function(){state.detailTid=null;return closeDrawerBase()};
async function waitTask(){for(let i=0;i<90;i++){const t=await loadTask();if(!t.running)return t;await new Promise(r=>setTimeout(r,1000))}}
async function loadTask(){const t=await api('/api/task');$('#sideStatus').textContent=t.message;$('#statusDot').classList.toggle('running',t.running);$('#taskPulse').classList.toggle('running',t.running);$('#taskMode').textContent=(t.mode||'IDLE').toUpperCase();$('#taskMessage').textContent=t.message;$('#taskProcessed').textContent=fmt(t.processed);$('#taskMatched').textContent=fmt(t.matched);$('#taskLastTid').textContent=t.last_tid||'—';$('#taskElapsed').textContent=(t.elapsed_seconds||0)+'s';$('#taskError').textContent=t.error||'';$('#taskProgress').classList.toggle('indeterminate',t.running);if(t.last_recorded_id){$('#syncLastId').textContent=t.last_recorded_id;$('#syncNextId').textContent=t.last_recorded_id+1}return t}
function hunterTaskHtml(t){const results=t.results||[],next=t.next_check_at?new Date(t.next_check_at).toLocaleTimeString('zh-CN',{hour12:false}):'—';return `<article class="hunter-task ${t.active?'active':''}" data-task-id="${attr(t.id)}"><div class="hunter-task-head"><div><span class="mode-badge ${t.active?'live':''}">${t.active?'RUNNING':'COMPLETED'}</span><strong>${esc(t.name)}</strong><small>${esc(t.config?.q||'')} · 每 ${t.config?.interval||60} 秒</small></div><div class="hunter-task-actions"><button class="button ghost hunter-task-edit" type="button">编辑</button>${t.active?'<button class="button danger hunter-task-stop" type="button">停止任务</button>':''}</div></div><p>${esc(t.message)}</p><div class="hunter-task-stats"><span>检查 <b>${fmt(t.checks)}</b></span><span>命中 <b>${fmt(t.total_matches)}</b></span><span>本轮新增 <b>${fmt(t.new_hits)}</b></span><span>下次 <b>${next}</b></span></div>${t.error?`<p class="task-error">${esc(t.error)}</p>`:''}${results.length?`<div class="hunter-results">${results.map(p=>`<div class="hunter-result ${p.search_excluded?'excluded-result':''}" data-tid="${p.tid}" data-query="${attr(t.config?.q||'')}"><div><strong>${esc(p.title)}</strong><small>${esc(p.username||'未知')} · TID ${p.tid}</small></div><span class="status-tag">${p.search_excluded?'排除':esc(p.category)}</span><span class="time-cell">${localTime(p.created_at)}</span></div>`).join('')}</div>`:''}</article>`}
async function loadHunter(){const h=await api('/api/hunter'),tasks=h.tasks||[];$('#hunterBadge').textContent=`${h.active_count||0} RUNNING`;$('#hunterBadge').classList.toggle('live',h.active);$('#hunterTaskCount').textContent=`${tasks.length} 个任务`;$('#hunterTasks').innerHTML=tasks.length?tasks.map(hunterTaskHtml).join(''):'<div class="daily-empty">创建猎手任务后将在这里显示</div>';$$('.hunter-result').forEach(row=>row.onclick=()=>showPost(row.dataset.tid,true,row.dataset.query||''));$$('.hunter-task-stop').forEach(button=>button.onclick=()=>stopHunter(button.closest('.hunter-task').dataset.taskId));$$('.hunter-task-edit').forEach(button=>button.onclick=()=>editHunter(tasks.find(t=>t.id===button.closest('.hunter-task').dataset.taskId)));for(const t of tasks){const previous=state.hunterAlerts[t.id];if(previous===undefined){state.hunterAlerts[t.id]=t.alert_id||0;continue}if((t.alert_id||0)>previous){state.hunterAlerts[t.id]=t.alert_id;const hits=t.latest_hits||[],message=hits.length?`“${t.name}”发现 ${hits.length} 条新结果`:`“${t.name}”任务已结束`;toast(message);if('Notification'in window&&Notification.permission==='granted')new Notification('SDGun 市场猎手任务',{body:hits[0]?.title||message,tag:`sdgun-hunter-${t.id}-${t.alert_id}`})}}return h}
function cancelHunterEdit(){state.hunterEditing=null;$('#hunterName').value='';$('#hunterQuery').value='';$('#hunterInterval').value='60';$('#hunterStart').textContent='创建猎手任务';$('#hunterEditCancel').hidden=true}
function editHunter(t){if(!t)return;state.hunterEditing=t.id;$('#hunterName').value=t.name||'';$('#hunterQuery').value=t.config?.q||'';$('#hunterMatch').value=t.config?.match||'any';$('#hunterField').value=t.config?.field||'all';$('#hunterPostType').value=t.config?.post_type||'二手出售';$('#hunterCategory').value=t.config?.category||'全部';$('#hunterInterval').value=String(t.config?.interval||60);$('#hunterStart').textContent='保存任务修改';$('#hunterEditCancel').hidden=false;$('#hunterName').focus();window.scrollTo({top:0,behavior:'smooth'})}
async function startHunter(){const q=$('#hunterQuery').value.trim();if(!q)return toast('请先输入猎手关键词');if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();const payload={name:$('#hunterName').value.trim(),q,match:$('#hunterMatch').value,field:$('#hunterField').value,post_type:$('#hunterPostType').value,category:$('#hunterCategory').value,interval:Number($('#hunterInterval').value||60)};try{const editing=state.hunterEditing;if(editing)payload.task_id=editing;const r=await api(editing?'/api/hunter/edit':'/api/hunter/start',{method:'POST',body:JSON.stringify(payload)});state.hunterAlerts[r.task.id]=r.task.alert_id||0;toast(r.message);cancelHunterEdit();await loadHunter()}catch(e){toast(e.message)}}
async function stopHunter(taskId){const r=await api('/api/hunter/stop',{method:'POST',body:JSON.stringify({task_id:taskId})});toast(r.message);await loadHunter()}
function navigate(id){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.target===id));$$('.section').forEach(x=>x.classList.toggle('active-section',x.id===id));if(id==='posts')loadPosts(true);if(id==='favorites')loadFavorites();if(id==='hunter')loadHunter();window.scrollTo({top:0})}
function updateSearchHint(){const mode=state.match==='all'?'每个关键词都必须':'任意关键词可以';const field={all:'出现在标题、作者、正文或物品明细中',title:'出现在帖子标题中',author:'出现在作者名称中'}[state.field];$('#searchHint').textContent=mode+field;$('#searchInput').placeholder=state.field==='title'?'输入一个或多个标题关键词':state.field==='author'?'输入一个或多个作者关键词':'多关键词：用空格、逗号或顿号分隔'}
function bindPostTypes(){$$('.type-filter').forEach(button=>button.onclick=()=>{$$('.type-filter').forEach(x=>x.classList.toggle('active',x===button));state.postType=button.dataset.postType;navigate('posts')});$('#syncPostType').value=state.syncPostType;$('#syncPostType').onchange=e=>{state.syncPostType=e.target.value;localStorage.setItem('sdgun-sync-post-type',state.syncPostType);toast(`拉取类型已设为${state.syncPostType}`)}}

function bind(){$$('.nav-item').forEach(x=>x.onclick=()=>navigate(x.dataset.target));$('#controlBtn').onclick=()=>navigate('control');$('#refreshBtn').onclick=()=>refreshLatest(true);$('#syncNow').onclick=()=>refreshLatest(true);$('#syncWorkers').value=String(state.workers);$('#syncWorkers').onchange=e=>{state.workers=Number(e.target.value);localStorage.setItem('sdgun-sync-workers',String(state.workers));toast(`同步并发已设为 ${state.workers} 线程`)};$('#hunterStart').onclick=startHunter;$('#hunterStop').onclick=stopHunter;$('#closeDrawer').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#lightboxClose').onclick=closeLightbox;$('#imageLightbox').onclick=e=>{if(e.target.id==='imageLightbox')closeLightbox()};$('#detailBody').onclick=e=>{const b=e.target.closest('.image-button');if(b)openLightbox(b.dataset.src,b.dataset.alt)};document.onkeydown=e=>{if(e.key==='Escape'){$('#imageLightbox').classList.contains('open')?closeLightbox():closeDrawer()}};$('#periodPicker').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#periodPicker button').forEach(x=>x.classList.toggle('active',x===b));state.days=Number(b.dataset.days);Promise.all([loadSummary(),loadDaily()])};$('#categoryFilter').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#categoryFilter button').forEach(x=>x.classList.toggle('active',x===b));state.category=b.dataset.category;loadPosts(true)};$('#matchMode').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#matchMode button').forEach(x=>x.classList.toggle('active',x===b));state.match=b.dataset.match;updateSearchHint();loadPosts(true)};$('#searchField').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#searchField button').forEach(x=>x.classList.toggle('active',x===b));state.field=b.dataset.field;updateSearchHint();loadPosts(true)};let searchTimer;$('#searchInput').oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=e.target.value.trim();loadPosts(true)},280)};$('#loadMore').onclick=()=>loadPosts(false);$('#stopTask').onclick=async()=>{const r=await api('/api/tasks/stop',{method:'POST',body:'{}'});toast(r.message);loadTask()};window.addEventListener('resize',()=>loadSummary());updateSearchHint()}
async function init(){state.openedAt=new Date();$('#openedAt').textContent=state.openedAt.toLocaleString('zh-CN',{hour12:false});bind();$('#hunterEditCancel').onclick=cancelHunterEdit;bindPostTypes();await Promise.all([loadSummary(),loadDaily(),loadPosts(true),loadTask(),loadHunter()]);setInterval(loadTask,2000);setInterval(loadHunter,5000);refreshLatest(false)}
init().catch(e=>toast(e.message));
